/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

/**
 *
 * @author Roy Palomino
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuCliente = new javax.swing.JMenuItem();
        MenuProducto = new javax.swing.JMenuItem();
        MenuEmpleado = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        VentaVender = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MenuCventas = new javax.swing.JMenuItem();
        MenuCproductos = new javax.swing.JMenuItem();
        MenuCclientes = new javax.swing.JMenuItem();
        MenuCempleados = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MenuRdiario = new javax.swing.JMenuItem();
        MenuRempleados = new javax.swing.JMenuItem();
        MenuRproductos = new javax.swing.JMenuItem();
        MenuRclientes = new javax.swing.JMenuItem();
        MenuRventas = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        Ayuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("SISTEMA DE VENTAS TIENDA LUCILA");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/supermercado.jpg"))); // NOI18N

        jMenuBar1.setBorder(null);

        jMenu1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        jMenu1.setText("SALIR");
        jMenu1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jMenuItem1.setText("Salir");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mantenimiento.jpg"))); // NOI18N
        jMenu2.setText("MANTENIMIENTO");
        jMenu2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        MenuCliente.setText("Cliente");
        MenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuClienteActionPerformed(evt);
            }
        });
        jMenu2.add(MenuCliente);

        MenuProducto.setText("Producto");
        MenuProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProductoActionPerformed(evt);
            }
        });
        jMenu2.add(MenuProducto);

        MenuEmpleado.setText("Empleado");
        MenuEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEmpleadoActionPerformed(evt);
            }
        });
        jMenu2.add(MenuEmpleado);

        jMenuBar1.add(jMenu2);

        jMenu3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carrito.png"))); // NOI18N
        jMenu3.setText("VENTA");
        jMenu3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        VentaVender.setText("Vender Productos");
        VentaVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentaVenderActionPerformed(evt);
            }
        });
        jMenu3.add(VentaVender);

        jMenuBar1.add(jMenu3);

        jMenu4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/consultar.png"))); // NOI18N
        jMenu4.setText("CONSULTA");
        jMenu4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        MenuCventas.setText("Ventas");
        MenuCventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCventasActionPerformed(evt);
            }
        });
        jMenu4.add(MenuCventas);

        MenuCproductos.setText("Productos");
        MenuCproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCproductosActionPerformed(evt);
            }
        });
        jMenu4.add(MenuCproductos);

        MenuCclientes.setText("Clientes");
        MenuCclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCclientesActionPerformed(evt);
            }
        });
        jMenu4.add(MenuCclientes);

        MenuCempleados.setText("Empleados");
        MenuCempleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCempleadosActionPerformed(evt);
            }
        });
        jMenu4.add(MenuCempleados);

        jMenuBar1.add(jMenu4);

        jMenu5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/notebook_32x32.png"))); // NOI18N
        jMenu5.setText("REPORTES");
        jMenu5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        MenuRdiario.setText("Reporte Diario");
        MenuRdiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRdiarioActionPerformed(evt);
            }
        });
        jMenu5.add(MenuRdiario);

        MenuRempleados.setText("Reporte Empleado");
        MenuRempleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRempleadosActionPerformed(evt);
            }
        });
        jMenu5.add(MenuRempleados);

        MenuRproductos.setText("Reporte Producto");
        MenuRproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRproductosActionPerformed(evt);
            }
        });
        jMenu5.add(MenuRproductos);

        MenuRclientes.setText("Reporte Clientes");
        MenuRclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRclientesActionPerformed(evt);
            }
        });
        jMenu5.add(MenuRclientes);

        MenuRventas.setText("Reporte Ventas");
        MenuRventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRventasActionPerformed(evt);
            }
        });
        jMenu5.add(MenuRventas);

        jMenuBar1.add(jMenu5);

        jMenu6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ayuda.png"))); // NOI18N
        jMenu6.setText("AYUDA");
        jMenu6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        Ayuda.setText("Acerca del Software");
        Ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AyudaActionPerformed(evt);
            }
        });
        jMenu6.add(Ayuda);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuClienteActionPerformed
      M_Cliente c1=new M_Cliente();
      c1.setVisible(true);
    }//GEN-LAST:event_MenuClienteActionPerformed

    private void MenuProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProductoActionPerformed
        M_Producto p1=new M_Producto();
        p1.setVisible(true);
    }//GEN-LAST:event_MenuProductoActionPerformed

    private void MenuEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEmpleadoActionPerformed
        M_Empleado e1=new M_Empleado();
        e1.setVisible(true);
    }//GEN-LAST:event_MenuEmpleadoActionPerformed

    private void VentaVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentaVenderActionPerformed
        Venta v1=new Venta();
        v1.setVisible(true);
    }//GEN-LAST:event_VentaVenderActionPerformed

    private void MenuCventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCventasActionPerformed
        C_Ventas v1=new C_Ventas();
        v1.setVisible(true);
    }//GEN-LAST:event_MenuCventasActionPerformed

    private void MenuCproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCproductosActionPerformed
        C_Productos p1=new C_Productos();
        p1.setVisible(true);
    }//GEN-LAST:event_MenuCproductosActionPerformed

    private void MenuCclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCclientesActionPerformed
        C_Clientes c1=new C_Clientes();
        c1.setVisible(true);
    }//GEN-LAST:event_MenuCclientesActionPerformed

    private void MenuCempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCempleadosActionPerformed
        C_Empleados e1=new C_Empleados();
        e1.setVisible(true);
    }//GEN-LAST:event_MenuCempleadosActionPerformed

    private void MenuRdiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRdiarioActionPerformed
        R_Diario d1=new R_Diario();
        d1.setVisible(true);
    }//GEN-LAST:event_MenuRdiarioActionPerformed

    private void MenuRempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRempleadosActionPerformed
        R_Empleado e1=new R_Empleado();
        e1.setVisible(true);
    }//GEN-LAST:event_MenuRempleadosActionPerformed

    private void MenuRproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRproductosActionPerformed
        R_Producto p1=new R_Producto();
        p1.setVisible(true);
    }//GEN-LAST:event_MenuRproductosActionPerformed

    private void MenuRclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRclientesActionPerformed
        R_Clientes c1=new R_Clientes();
        c1.setVisible(true);
    }//GEN-LAST:event_MenuRclientesActionPerformed

    private void MenuRventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRventasActionPerformed
        R_Ventas v1=new R_Ventas();
        v1.setVisible(true);
    }//GEN-LAST:event_MenuRventasActionPerformed

    private void AyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AyudaActionPerformed
        Acerca_S t1=new Acerca_S();
        t1.setVisible(true);
    }//GEN-LAST:event_AyudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Ayuda;
    private javax.swing.JMenuItem MenuCclientes;
    private javax.swing.JMenuItem MenuCempleados;
    private javax.swing.JMenuItem MenuCliente;
    private javax.swing.JMenuItem MenuCproductos;
    private javax.swing.JMenuItem MenuCventas;
    private javax.swing.JMenuItem MenuEmpleado;
    private javax.swing.JMenuItem MenuProducto;
    private javax.swing.JMenuItem MenuRclientes;
    private javax.swing.JMenuItem MenuRdiario;
    private javax.swing.JMenuItem MenuRempleados;
    private javax.swing.JMenuItem MenuRproductos;
    private javax.swing.JMenuItem MenuRventas;
    private javax.swing.JMenuItem VentaVender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
